  spring:
  datasource:
    url: jdbc:sqlite:./employees.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: employee-service
server:
  port: 8081
logging:
  level:
    org.springframework.web: debug
    org.hibernate: error
