api-gw.url-microservicio-employees: http://localhost:8081
api-gw.url-microservicio-pruebas: http://localhost:8082
api-gw.url-microservicio-notificaciones: http://localhost:8083
server:
  port: 8080

spring:
  main:
    web-application-type: reactive