api-gw.url-microservicio-employees: http://localhost:8081
api-gw.url-microservicio-pruebas: http://localhost:8082
api-gw.url-microservicio-notificaciones: http://localhost:8083
server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: cliente-tpi
            client-secret: ZmiMMce6zh4xKHde1FFKbfkiThDyYpyn
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      resourceserver:
          jwt:
            issuer-uri:  https://labsys.frc.utn.edu.ar/aim/
