api-gw:
  url-microservicio-employees: http://localhost:8081
  url-microservicio-pruebas: http://localhost:8082
  url-microservicio-notificaciones: http://localhost:8083

server:
  port: 8080

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://labsys.frc.utn.edu.ar/aim/realms/backend-tps
