spring:
  datasource:
    url: jdbc:sqlite:./pruebas.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: pruebas-service
server:
  port: 8082
external:
  api-url: https://labsys.frc.utn.edu.ar/apps-disponibilizadas/backend/api/v1/configuracion/
  gateway-url: https://localhost:8081