spring:
  datasource:
    url: jdbc:sqlite:./notificaciones.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: notificaciones-service
server:
  port: 8083
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    user: tpbackend7@gmail.com
    password: -----
    starttls:
      enable: true